#!/bin/bash

TZ="$(date +%z)"
TZ_SIGN=${TZ:0:1}
TZ_HOUR=${TZ:1:2}
TZ_MIN=${TZ:3:2}

FF="$TZ_SIGN $(( $((TZ_HOUR*3600)) + $((TZ_MIN*60)) ))"

SERIAL="/dev/$(dmesg |grep 'FTDI.*attached to ttyUSB' |tail -1 |sed 's|^.*ttyUSB|ttyUSB|')"

stty -F "${SERIAL}" raw ispeed 19200 ospeed 19200
exec 5<>"${SERIAL}"
read -r -t 5 -u 5 -n 255
printf "\xFFST%s" "$(( $(date +%s) + FF ))" >&5
exec 5>&-
